### ISSUE TITLE
[1.18.1] Would it be possible to not let the zoom out value go past normal fov?

### ISSUE THREAD

**Issue by Gbergz** [Keksuccino/JustZoom#1]
Title ^

Zooming Out past your normal fov makes the game like this:
![image](https://user-images.githubusercontent.com/26634554/148819327-3a99fdef-d7e8-421b-bb2f-aa756a725db8.png)

Not a big issue I guess. Thought I would point it out though!
**-** Gbergz

**Comment by Keksuccino** [comment]
I didn't remove this on purpose lmao
I thought it's a funny thing :‘D

**Comment by Gbergz** [comment]
It made me giggle not gonna lie. :D

**Comment by Keksuccino** [comment]
Improved in Just Zoom v1.0.1! Thank you for your report!
