### ISSUE TITLE
[1.16.5 Forge] Crash, Java 17 is not valid for this version

### ISSUE THREAD

**Issue by Kaleidio** [Keksuccino/JustZoom#12]
```[15Jul2023 09:11:44.724] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.1 (ASM10_EXPERIMENTAL))```

This is a common error if your cross platform codebases try to common a build config

**Comment by Keksuccino** [comment]
Well, it's more a "I quickly copy-pasted everything from A to B without testing and forgot to change the string"-problem..

Will fix that later today, thank you for telling me!

**Comment by Kaleidio** [comment]
ahh haha yeah that too

**Comment by Keksuccino** [comment]
Fixed in v1.0.2-2! :)
