### ISSUE TITLE
JustZoom reports server incompatible unless included server-side too

### ISSUE THREAD

**Issue by C-512L** [Keksuccino/JustZoom#13]
I'm not a forge mod developer but I suppose that is either that Modrinth information is wrong about requiring it server-side, or that the mod doesn't report itself correctly as client-side only to forge:
```
[28Aug2023 21:19:39.106] [Netty Client IO #0/INFO] [net.minecraftforge.client.ForgeHooksClient/CLIENTHOOKS]: Client has mods that are missing on server: [justzoom]
```

**Comment by Keksuccino** [comment]
The mod got a full rewrite. If this is still happening, please open a new issue, thank you very much.
