### ISSUE TITLE
Zoom Smoothing [Feature request]

### ISSUE THREAD

**Issue by StormDragon-64** [Keksuccino/JustZoom#2]
I think that this would look much better if there were smooth transitions when scrolling instead of it snapping to the next zoom position when you scroll.

**Comment by jakesnek** [comment]
I agree with this :D just downloaded the mod and really would love this as I am so confused when it comes to minecraft modding.

**Comment by Keksuccino** [comment]
Added in Just Zoom v1.0.2!

**Comment by StormDragon-64** [comment]
How do I enable this? I can't find an option for it in the config.

**Comment by Keksuccino** [comment]
It's `lerp_amount` and is enabled by default.
Keep in mind you need to be on v1.0.2.

**Comment by StormDragon-64** [comment]
oh, it's not a thing on 1.19.2, that's why.
