### ISSUE TITLE
Game crashes when I use the zoom key

### ISSUE THREAD

**Issue by thognaught** [Keksuccino/JustZoom#20]
Whenever I use the zoom key, the game will immediately crash and give me the following exit code when it crashes: -805306369. It does not have a crash log. I tried increasing the amount of memory Minecraft can use, and it gave me the same code. The older version of the mod does work fine, but I like the improvements on the new version a lot better.

EDIT: It works, but only when I have played for several minutes. Zooming a few seconds after joining will 100% crash the game.

**Comment by Keksuccino** [comment]
Please send your `logs/latest.log` file after the game crashes.

**Comment by Keksuccino** [comment]
Closed because no response and not reproducible.

**Comment by insberr** [comment]
I am experiencing this issue as well, but I have some details.
Minecraft version `1.20.1` using Forge version `47.3.12` and `justzoom_forge_2.0.0_MC_1.20.1.jar`

Here are the logs while the game is running:
![image](https://github.com/user-attachments/assets/25f00dce-7103-47f7-88aa-bb413d1b5389)
The last two logs `Invalid entity rotation: NaN, discarding.` happen after pressing the zoom key and the game freezes (no crash) and upon force quitting I get the exit code `-805306369`.
