### ISSUE TITLE
Version 2.0.0 not working with latest NeoForge for MC 1.20.1

### ISSUE THREAD

**Issue by RaeTheGit** [Keksuccino/JustZoom#21]
Previous version of JustZoom (1.0.2) worked fine with NeoForge (current latest version: 47.1.106) on MC 1.20.1. The update of JustZoom to 2.0.0 complains about Forge being outdated.
This looks to me like a version tagging issue either way as either the mod erroneously says it's not working on NeoForge 47.1.106, or Modrinth erroneously has registered the mod for 1.20.1 NeoForge.

**Comment by Keksuccino** [comment]
Don't use the mod on NeoForge 1.20.1 then. Not even the NeoForge team recommends using NeoForge on MC 1.20.1. It is recommended to use Forge on any version below 1.20.2.
