### ISSUE TITLE
Revert Third Person Zoom

### ISSUE THREAD

**Issue by Chris6ix** [Keksuccino/JustZoom#22]
Hey, I just updated JustZoom in my modpack and I noticed that the third person zoom is weird now. I can't zoom into my character anymore. Please revert the third person zoom to how it was in v1.0.2. I really like the in game config screen of v2.0.0, but I MUCH prefer the third person zooming of v1.0.2, so if you could revert to that (Or at least add a setting to re-enable that behavior), that would be amazing.

**Comment by Keksuccino** [comment]
There was no actual third-person zoom in v1.X.X. You just zoomed into your character and saw nothing (because you were looking at the zoomed character). This was a bug fix and I will not revert a fix, sorry.
