### ISSUE TITLE
Why do I need Koncrete to use Just zoom?

### ISSUE THREAD

**Issue by WrittenSkate** [Keksuccino/JustZoom#24]
In your forge page, it never said anywhere that it needs a mod called Konkrete, and when I boot minecraft it says "Just zoom needs mod konkrete 1.8.0 or newer". WHY?!?

**Comment by Keksuccino** [comment]
Because it's a dependency, ma guy.

<img width="566" alt="Screenshot_1" src="https://github.com/user-attachments/assets/66880940-8cf6-49ea-a3a6-656b95f6abb9">


<img width="728" alt="Screenshot_2" src="https://github.com/user-attachments/assets/261251a0-ed12-4786-a770-4946ca6e40ee">
